### ISSUE TITLE
Various timeouts throughout Ekylibre.

### ISSUE THREAD

**Issue by Aquaj** [ekylibre/ekylibre#1255]
- [x] Timeouts on global search with a lot of data. (#1052)  (Deactivated global search for now)
- [ ] Timeouts on Archive > documents#index. (#950)
- [ ] Timeouts on Inventory refreshing.
- [ ] Timeouts on document generation. (#822)
